### ISSUE TITLE
Add metadata to the venue page

### ISSUE THREAD

**Issue by nuest** [codecheckers/register#84]
Depends on #79 and may better be split up into multiple issues when started.

The venue landing page should show some minimal metadata about the venue. Currently, the page only lists the checks:

https://codecheck.org.uk/register/venues/conference/AGILEGIS/

![image](https://github.com/user-attachments/assets/352b8338-9769-4981-b3c5-94c35216bf97)

It should also provide the following information:

- contact email regarding CODECHECK
- URL
- logo via an external logo URL (we don't host the logos)
- short description
- identifier(s), such as ISSN, ROR, event identifiers (ConfIDent), ...

The final page cold look something like this:

![image](https://github.com/user-attachments/assets/57e4093d-a234-4ab5-9a60-4ff94f50f066)

The information should be stored in plain text files in the register, e.g. in a folder `venues` with YML files, such as `gigascience.yml`:

```yml
type: journal
contact:
	name: Edd Editor
	email: edd@giga.science
url: https://giga.science
logo-url: https://giga.science/logo.png
identifiers:
 	- name: ROR
 	  value: bla
      link: http://ror.org/bla
    - name: ISSN
      value: 1234-5678
  	  link: https://issn.org/1234-5678
description: |
	The journal is...
```
